/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package yazlab;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import static yazlab.login.studentData;

/**
 *
 * @author Aylin
 */
public class derstalepgörüntüle extends javax.swing.JInternalFrame {
  Connection baglan; 
  PreparedStatement pat;
  ResultSet rs;
  int q,i;
    /**
     * Creates new form dersSecimi
     */
    public derstalepgörüntüle() {
        initComponents();
         baglantiAc();
        derstaleptablo();
       
    }
  public void derstaleptablo(){
            try {
       
               pat=baglan.prepareStatement("SELECT*FROM derstalepanlasma");
               rs=pat.executeQuery();
               DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
               ResultSetMetaData stveri=rs.getMetaData();
               
               q=stveri.getColumnCount();
               DefaultTableModel RecordTable=(DefaultTableModel)jTable1.getModel();
               RecordTable.setRowCount(0);
               while(rs.next()){
                   Vector sutunVeri=new Vector();
                  // Object[] studentData=new Object[q];
                   for(i =1;i<=q;i++){
                       sutunVeri.add(rs.getString("id"));
                       sutunVeri.add(rs.getString("ogrenciid"));
                        sutunVeri.add(rs.getString("ogrenciad"));
                       sutunVeri.add(rs.getString("hocaad"));
                       sutunVeri.add(rs.getString("anlasmadurumu"));
                       sutunVeri.add(rs.getString("iletilenmesaj"));
                        sutunVeri.add(rs.getString("dersad"));
                       
                   }
                   RecordTable.addRow(sutunVeri);
                   
               }
               
               jTable1.setModel(model);
             
           } catch (SQLException ex) {
               Logger.getLogger(ogrenciekle.class.getName()).log(Level.SEVERE, null, ex);
           }
     
    }
  public void baglantiAc(){
       try{
    Class.forName("org.postgresql.Driver");
     String bag="jdbc:postgresql://localhost:5432/YAZLAB";
     String username="postgres";
     String sifre="6842";
     baglan= DriverManager.getConnection(bag,username,sifre);
  
   // JOptionPane.showMessageDialog(null, "veri tabani baglantisi basarili");
   
       }
       catch (ClassNotFoundException ex) {
            Logger.getLogger(derstalepgörüntüle.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(derstalepgörüntüle.class.getName()).log(Level.SEVERE, null, ex);
        }
       
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(102, 255, 204));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "ogrenciid", "ogrenciad", "hocaad", "anlasmadurumu", "iletilenmesaj", "dersad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(768, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
