/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package yazlab;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aylin
 */
public class ilgialaniekleme extends javax.swing.JInternalFrame {

    /**
     * Creates new form ilgialaniekleme
     */
    public ilgialaniekleme() {
        initComponents();
        baglantiAc();
        comboxilgialaniid();
        comboxilgialaniEkle();
        tablo();
        
        
    }
 Connection baglan; 
  PreparedStatement pat;
  ResultSet rs;
  int q,i;
  

     public void comboxilgialaniEkle(){
          try {
        pat=baglan.prepareStatement("SELECT*FROM ogrenci");
        rs=pat.executeQuery();
        while(rs.next()){
       jComboBoxogrenciid.addItem(rs.getString("id"));
    }
         }catch (SQLException ex) {
        Logger.getLogger(hocaekle.class.getName()).log(Level.SEVERE, null, ex);
    }
      jComboBoxogrenciid.setSelectedIndex(-1);
   }
     
     
        public void comboxilgialaniid(){
          try {
        pat=baglan.prepareStatement("SELECT*FROM ilgialani");
        rs=pat.executeQuery();
        while(rs.next()){
        jComboBoxilgialaniid.addItem(rs.getString("id"));
    }
         }catch (SQLException ex) {
        Logger.getLogger(hocaekle.class.getName()).log(Level.SEVERE, null, ex);
    }
        jComboBoxilgialaniid.setSelectedIndex(-1);
   }
        
        
    public void tablo(){
               try {
            pat=baglan.prepareStatement("SELECT*FROM ilgialani");
             rs=pat.executeQuery();
             DefaultTableModel model=(DefaultTableModel) jTable1.getModel();
            ResultSetMetaData stveri=rs.getMetaData();
            
            q=stveri.getColumnCount();
            DefaultTableModel RecordTable=(DefaultTableModel)jTable1.getModel();
               RecordTable.setRowCount(0);
             while(rs.next()){
                 Vector sutunVeri=new Vector();
                 for(i =1;i<=q;i++){
                     sutunVeri.add(rs.getString("id"));
                     sutunVeri.add(rs.getString("ilgialani"));
                     sutunVeri.add(rs.getString("ogrenciid"));
                   
                 }
                 RecordTable.addRow(sutunVeri);
                 
             }       
            
          jTable1.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(ogrenciekle.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   public void baglantiAc(){
       try{
    Class.forName("org.postgresql.Driver");
     String bag="jdbc:postgresql://localhost:5432/YAZLAB";
     String username="postgres";
     String sifre="6842";
     baglan= DriverManager.getConnection(bag,username,sifre);
  
   // JOptionPane.showMessageDialog(null, "veri tabani baglantisi basarili");
   
       }
       catch (ClassNotFoundException ex) {
            Logger.getLogger(ogrenciekle.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ogrenciekle.class.getName()).log(Level.SEVERE, null, ex);
        }
       
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldilgialani = new javax.swing.JTextField();
        jComboBoxogrenciid = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jButtonEKLE = new javax.swing.JButton();
        jButtonGUNCELLE = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jComboBoxilgialaniid = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        jLabel1.setText("İlgi Alani:");

        jTextFieldilgialani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldilgialaniActionPerformed(evt);
            }
        });

        jLabel2.setText("Ogrenci id:");

        jButtonEKLE.setText("EKLE");
        jButtonEKLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEKLEActionPerformed(evt);
            }
        });

        jButtonGUNCELLE.setText("GUNCELLE");
        jButtonGUNCELLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGUNCELLEActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "ilgialani", "ogrenciid"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel3.setText("İD:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldilgialani, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxogrenciid, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonEKLE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonGUNCELLE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxilgialaniid, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(415, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldilgialani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxogrenciid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonEKLE)
                    .addComponent(jButtonGUNCELLE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBoxilgialaniid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addContainerGap(669, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldilgialaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldilgialaniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldilgialaniActionPerformed

    private void jButtonEKLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEKLEActionPerformed
        // TODO add your handling code here:
        ilgialaniManager ilgi=new ilgialaniManager();
        ilgi.insert(jTextFieldilgialani.getText(), Integer.parseInt((String) jComboBoxogrenciid.getSelectedItem()));
        comboxilgialaniEkle();
        tablo();
       jTextFieldilgialani.setText("");


    }//GEN-LAST:event_jButtonEKLEActionPerformed

    private void jButtonGUNCELLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGUNCELLEActionPerformed
        // TODO add your handling code here:
        
         String id=jComboBoxilgialaniid.getSelectedItem().toString();
        int ilgiid=Integer.parseInt(id);
          ilgialaniManager ilgi=new ilgialaniManager();
          ilgi.update(jTextFieldilgialani.getText(), Integer.parseInt((String) jComboBoxogrenciid.getSelectedItem()), ilgiid);
            comboxilgialaniEkle();
            tablo();
            jTextFieldilgialani.setText("");
            jComboBoxogrenciid.setSelectedIndex(-1);
            jTextFieldilgialani.requestFocus();
        
        
    }//GEN-LAST:event_jButtonGUNCELLEActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEKLE;
    private javax.swing.JButton jButtonGUNCELLE;
    private javax.swing.JComboBox<String> jComboBoxilgialaniid;
    private javax.swing.JComboBox<String> jComboBoxogrenciid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldilgialani;
    // End of variables declaration//GEN-END:variables
}
