/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package yazlab;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Aylin
 */
public class ogrenciyedersekle extends javax.swing.JInternalFrame {

    /**
     * Creates new form ogrenciyedersekle
     */
    public ogrenciyedersekle() {
        initComponents();
        baglantiAc();
        idders();
        comboxDersEkle();
        tablo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTableogrenciders = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFielddersad = new javax.swing.JTextField();
        jTextFielddersharfnot = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxdersid = new javax.swing.JComboBox<>();
        ARAMA = new javax.swing.JButton();
        jComboBoxDersekleme = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jButtonEKLE = new javax.swing.JButton();
        jButtonGUNCELLE = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 153, 255));

        jTableogrenciders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "dersid", "dersad", "dersharfnot", "ogrenciid"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTableogrenciders);

        jLabel1.setText("ders ad");

        jLabel2.setText("dersharfnot");

        jTextFielddersad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFielddersadActionPerformed(evt);
            }
        });

        jLabel4.setText("ders id:");

        jComboBoxdersid.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        ARAMA.setText("ARAMA");
        ARAMA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ARAMAActionPerformed(evt);
            }
        });

        jLabel5.setText("ogrenci id:");

        jButtonEKLE.setText("EKLE");
        jButtonEKLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEKLEActionPerformed(evt);
            }
        });

        jButtonGUNCELLE.setText("GUNCELLE");
        jButtonGUNCELLE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGUNCELLEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxDersekleme, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(110, 110, 110)
                        .addComponent(jButtonEKLE)
                        .addGap(34, 34, 34)
                        .addComponent(jButtonGUNCELLE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFielddersad, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(83, 83, 83)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFielddersharfnot, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ARAMA)
                            .addComponent(jComboBoxdersid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(479, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(212, 212, 212))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBoxdersid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextFielddersad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFielddersharfnot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ARAMA)))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEKLE)
                    .addComponent(jButtonGUNCELLE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBoxDersekleme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  Connection baglan; 
  PreparedStatement pat;
  ResultSet rs;
  int q,i;
   
   public void baglantiAc(){
       try{
    Class.forName("org.postgresql.Driver");
     String bag="jdbc:postgresql://localhost:5432/YAZLAB";
     String username="postgres";
     String sifre="6842";
     baglan= DriverManager.getConnection(bag,username,sifre);
  
   // JOptionPane.showMessageDialog(null, "veri tabani baglantisi basarili");
   
       }
       catch (ClassNotFoundException ex) {
            Logger.getLogger(ogrenciekle.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ogrenciekle.class.getName()).log(Level.SEVERE, null, ex);
        }
       
   }
    public void comboxDersEkle(){
          try {
        pat=baglan.prepareStatement("SELECT*FROM ogrenci");
        rs=pat.executeQuery();
        while(rs.next()){
       jComboBoxDersekleme.addItem(rs.getString("id"));
    }
         }catch (SQLException ex) {
        Logger.getLogger(hocaekle.class.getName()).log(Level.SEVERE, null, ex);
    }
       jComboBoxDersekleme.setSelectedIndex(-1);
   }
    
      private void idders() {
           try {
            pat=baglan.prepareStatement("SELECT dersid FROM ders");
            rs=pat.executeQuery();
           jComboBoxdersid.removeAllItems();
            while(rs.next()){
                
                jComboBoxdersid.addItem(rs.getString(1));
            }
        } catch (SQLException ex) {
            Logger.getLogger(ogrenciekle.class.getName()).log(Level.SEVERE, null, ex);
        }
          jComboBoxdersid.setSelectedIndex(-1);
    }
      
       public void tablo(){
       try {
            pat=baglan.prepareStatement("SELECT*FROM ders");
             rs=pat.executeQuery();
             DefaultTableModel model=(DefaultTableModel) jTableogrenciders.getModel();
            ResultSetMetaData stveri=rs.getMetaData();
            
            q=stveri.getColumnCount();
            DefaultTableModel RecordTable=(DefaultTableModel)jTableogrenciders.getModel();
               RecordTable.setRowCount(0);
             while(rs.next()){
                 Vector sutunVeri=new Vector();
                 for(i =1;i<=q;i++){
                     sutunVeri.add(rs.getString("dersid"));
                     sutunVeri.add(rs.getString("dersad"));
                     sutunVeri.add(rs.getString("dersharfnot"));
                     sutunVeri.add(rs.getString("ogrenciid"));
                   
                 }
                 RecordTable.addRow(sutunVeri);
                 
             }       
            
           jTableogrenciders.setModel(model);
        } catch (SQLException ex) {
            Logger.getLogger(ogrenciekle.class.getName()).log(Level.SEVERE, null, ex);
        }
   }
    private void jTextFielddersadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFielddersadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFielddersadActionPerformed

    private void ARAMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ARAMAActionPerformed
        // TODO add your handling code here:
           try {
            // TODO add your handling code here:

            String dersid=jComboBoxdersid.getSelectedItem().toString();
          int dersidd=  Integer.parseInt(dersid);
            pat=baglan.prepareStatement("SELECT*FROM ders WHERE dersid=?");
           pat.setInt(1, dersidd);
            
            rs=pat.executeQuery();
            if(rs.next()==true){
               jTextFielddersad.setText(rs.getString(2));
               jTextFielddersharfnot.setText(rs.getString(3));
     
              
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(ogrenci.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_ARAMAActionPerformed

    private void jButtonEKLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEKLEActionPerformed
        // TODO add your handling code here:
        dersManager dersmanager=new dersManager();
        dersmanager.insert(jTextFielddersad.getText(), jTextFielddersharfnot.getText(), Integer.parseInt((String) jComboBoxDersekleme.getSelectedItem()));
         comboxDersEkle();
        tablo();
         jTextFielddersad.setText("");
          jTextFielddersharfnot.setText("");
        
        
    }//GEN-LAST:event_jButtonEKLEActionPerformed

    private void jButtonGUNCELLEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGUNCELLEActionPerformed
        // TODO add your handling code here:
        String oyuncuid=jComboBoxdersid.getSelectedItem().toString();
        int dersid=Integer.parseInt(oyuncuid);
         dersManager dersmanager=new dersManager();
        dersmanager.update(jTextFielddersad.getText(), jTextFielddersharfnot.getText(),Integer.parseInt((String) jComboBoxDersekleme.getSelectedItem()),dersid);
        comboxDersEkle();
        tablo();
           jTextFielddersad.setText("");
          jTextFielddersharfnot.setText("");
          jComboBoxDersekleme.setSelectedIndex(0);
         jTextFielddersad.requestFocus();
        
    }//GEN-LAST:event_jButtonGUNCELLEActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ARAMA;
    private javax.swing.JButton jButtonEKLE;
    private javax.swing.JButton jButtonGUNCELLE;
    private javax.swing.JComboBox<String> jComboBoxDersekleme;
    private javax.swing.JComboBox<String> jComboBoxdersid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableogrenciders;
    private javax.swing.JTextField jTextFielddersad;
    private javax.swing.JTextField jTextFielddersharfnot;
    // End of variables declaration//GEN-END:variables
}
