/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package yazlab;

/**
 *
 * @author Aylin
 */
public class yoneticiarayuz extends javax.swing.JFrame {

    /**
     * Creates new form YoneticiArayuz
     */
    public yoneticiarayuz() {
        initComponents();
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButtonOgrEkle1 = new javax.swing.JButton();
        jButtonHocaEkle2 = new javax.swing.JButton();
        jButtonOgrEkle2 = new javax.swing.JButton();
        jButtonderstalep = new javax.swing.JButton();
        jButtoncıkıs = new javax.swing.JButton();
        jButtonilgialani = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));

        jDesktopPane1.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopPane1.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 959, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
        );

        jButtonOgrEkle1.setBackground(new java.awt.Color(204, 204, 204));
        jButtonOgrEkle1.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jButtonOgrEkle1.setForeground(new java.awt.Color(204, 51, 0));
        jButtonOgrEkle1.setText("Ogrenci Ekleme");
        jButtonOgrEkle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOgrEkle1ActionPerformed(evt);
            }
        });

        jButtonHocaEkle2.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jButtonHocaEkle2.setForeground(new java.awt.Color(204, 51, 0));
        jButtonHocaEkle2.setText("Hoca Ekleme");
        jButtonHocaEkle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHocaEkle2ActionPerformed(evt);
            }
        });

        jButtonOgrEkle2.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jButtonOgrEkle2.setForeground(new java.awt.Color(204, 51, 0));
        jButtonOgrEkle2.setText("Ogrenciye Ders Ekle");
        jButtonOgrEkle2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOgrEkle2ActionPerformed(evt);
            }
        });

        jButtonderstalep.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jButtonderstalep.setForeground(new java.awt.Color(204, 51, 0));
        jButtonderstalep.setText("Talep İşlemleri");
        jButtonderstalep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonderstalepActionPerformed(evt);
            }
        });

        jButtoncıkıs.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jButtoncıkıs.setForeground(new java.awt.Color(204, 51, 0));
        jButtoncıkıs.setText("çıkıs");
        jButtoncıkıs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtoncıkısActionPerformed(evt);
            }
        });

        jButtonilgialani.setFont(new java.awt.Font("Arial Black", 1, 10)); // NOI18N
        jButtonilgialani.setForeground(new java.awt.Color(204, 51, 0));
        jButtonilgialani.setText("İlgi Alani Ekleme");
        jButtonilgialani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonilgialaniActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jButtonOgrEkle1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButtonderstalep, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                .addComponent(jButtonHocaEkle2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jButtonOgrEkle2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonilgialani, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jButtoncıkıs, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jButtonOgrEkle1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButtonHocaEkle2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButtonderstalep, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jButtonOgrEkle2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jButtonilgialani, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jButtoncıkıs, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonHocaEkle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHocaEkle2ActionPerformed
        // TODO add your handling code here:
           hocaekle hocaekle=new hocaekle();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(hocaekle).setVisible(true);
    }//GEN-LAST:event_jButtonHocaEkle2ActionPerformed

    private void jButtonOgrEkle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOgrEkle1ActionPerformed
        // TODO add your handling code here:
        
        ogrenciekle ogrenciekle=new ogrenciekle();
        jDesktopPane1.removeAll();
        jDesktopPane1.add(ogrenciekle).setVisible(true);
    }//GEN-LAST:event_jButtonOgrEkle1ActionPerformed

    private void jButtonOgrEkle2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOgrEkle2ActionPerformed
        // TODO add your handling code here:
        ogrenciyedersekle odersekle=new ogrenciyedersekle();
         jDesktopPane1.removeAll();
        jDesktopPane1.add(odersekle).setVisible(true);
    }//GEN-LAST:event_jButtonOgrEkle2ActionPerformed

    private void jButtonderstalepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonderstalepActionPerformed
        // TODO add your handling code here:
        
        derstalepgörüntüle dtg=new derstalepgörüntüle();
         jDesktopPane1.removeAll();
          jDesktopPane1.add(dtg).setVisible(true);
        
        
    }//GEN-LAST:event_jButtonderstalepActionPerformed

    private void jButtoncıkısActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtoncıkısActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtoncıkısActionPerformed

    private void jButtonilgialaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonilgialaniActionPerformed
        // TODO add your handling code here:
        ilgialaniekleme ilgi=new ilgialaniekleme();
          jDesktopPane1.removeAll();
          jDesktopPane1.add(ilgi).setVisible(true); 
    }//GEN-LAST:event_jButtonilgialaniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(yoneticiarayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(yoneticiarayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(yoneticiarayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(yoneticiarayuz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new yoneticiarayuz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHocaEkle2;
    private javax.swing.JButton jButtonOgrEkle1;
    private javax.swing.JButton jButtonOgrEkle2;
    private javax.swing.JButton jButtoncıkıs;
    private javax.swing.JButton jButtonderstalep;
    private javax.swing.JButton jButtonilgialani;
    private javax.swing.JDesktopPane jDesktopPane1;
    // End of variables declaration//GEN-END:variables
}
